### ISSUE TITLE
Como utilizar aph ou apl

### ISSUE THREAD

**Issue by tgmti** [danielflira/advplayl#3]
No Readme indica Como utilizar:

Após a configuração apenas acessar em seu browser:
http://localhost/h_editor.aph
http://localhost/u_explorer.aph

Indicando a extenção .aph

porém, seguindo as instruções, só consegui acessar utilizando a extenção .apl

Será o meu ambiente que configurei errado? ou deveríamos mudar as instruções?

Ferramenta muito útil, estou usando bastante.

Parabéns!

**Comment by danielflira** [comment]
A documentação que estava errada, já foi corrigida

Vlw!
